In [100]:
import torch
import numpy as np

In [101]:
x =  torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [102]:
y = torch.tensor([[1, 2, 3],[4, 5, 6]])
y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [103]:
print(x.size())
print(y.size())

torch.Size([3])
torch.Size([2, 3])


In [104]:
x[0] += 10
print(x)

tensor([11,  2,  3])


In [105]:
print(x[0])

tensor(11)


In [106]:
x0_val = x[0].item()
print(x0_val)

11


Ejemplo de tensores

In [107]:
z = torch.ones(2,3)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [108]:
z = torch.rand(2, 3)
print(z)

tensor([[0.9978, 0.5104, 0.2318],
        [0.8710, 0.5617, 0.9391]])


In [109]:
z = torch.empty(2, 3)
print(z)

tensor([[-2.2226e-16,  7.8753e-43, -0.0000e+00],
        [ 1.7117e+00,  3.6893e+19,  1.8240e+00]])


### Que es un tensor?

Un tensor es una estructura de datos que generaliza los conceptos de escalares, vectores y matrices a dimensiones superiores. En términos simples:
- Un escalar es un tensor de orden 0 (un solo número).
- Un vector es un tensor de orden 1 (una lista de números).
- Una matriz es un tensor de orden 2 (una tabla de números con filas y columnas).

Un tensor puede tener más de dos dimensiones, lo que permite representar datos más complejos, como imágenes (3D), videos (4D) o cualquier otro tipo de datos multidimensionales. Los tensores son fundamentales en el aprendizaje profundo y se utilizan para almacenar y manipular datos en redes neuronales.

In [110]:
a = torch.tensor(-5.3)
print(a.size)
print(a)

<built-in method size of Tensor object at 0x000001B5325A4EB0>
tensor(-5.3000)


In [111]:
a = torch.ones(2,3)
print(a.size())
print(a)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


La función `torch.ones(3, 4, 5)` crea un tensor de tres dimensiones (3D) donde:

- El primer número (`3`) indica que hay 3 bloques o matrices.
- El segundo número (`4`) indica que cada bloque tiene 4 filas.
- El tercer número (`5`) indica que cada fila tiene 5 columnas.

En términos generales, un tensor de forma `(3, 4, 5)` puede visualizarse como una colección de 3 matrices, cada una de tamaño 4x5. Más allá de matrices, los tensores permiten representar datos multidimensionales, como imágenes (por ejemplo, lotes de imágenes RGB pueden tener forma `(batch_size, canales, alto, ancho)`).

**Resumen:**  
- Escalar: tensor de 0 dimensiones (un solo número).
- Vector: tensor de 1 dimensión (una lista).
- Matriz: tensor de 2 dimensiones (tabla de números).
- Tensor 3D: colección de matrices (por ejemplo, `torch.ones(3, 4, 5)`).

Esto es útil en aprendizaje profundo para organizar datos complejos y trabajar con lotes de ejemplos, canales de color, secuencias, etc.

In [112]:
a = torch.ones(3,4,5)
print(a.size())
print(a)

torch.Size([3, 4, 5])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [113]:
# 2 Grupos de 3 matrices de 4x5
a = torch.ones(2,3,4,5)
print(a.size())
print(a)

torch.Size([2, 3, 4, 5])
tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


In [114]:
a = torch.ones(2,3,4,5,2)
print(a.size())
print(a)

torch.Size([2, 3, 4, 5, 2])
tensor([[[[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

     

### Operaciones aritméticas básicas con tensores en PyTorch

A continuación se muestran ejemplos de suma, resta, multiplicación, división y operaciones elemento a elemento entre tensores.

In [115]:
# Suma, resta, multiplicación y división elemento a elemento
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

suma = x + y
resta = x - y
producto = x * y
division = x / y

print('Suma:', suma)
print('Resta:', resta)
print('Producto:', producto)
print('División:', division)

Suma: tensor([5., 7., 9.])
Resta: tensor([-3., -3., -3.])
Producto: tensor([ 4., 10., 18.])
División: tensor([0.2500, 0.4000, 0.5000])


In [116]:
# Otras operaciones: potencia, raíz cuadrada, suma total, media
potencia = x ** 2
raiz = torch.sqrt(x)
suma_total = torch.sum(x)
media = torch.mean(x)

print('Potencia:', potencia)
print('Raíz cuadrada:', raiz)
print('Suma total:', suma_total)
print('Media:', media)

Potencia: tensor([1., 4., 9.])
Raíz cuadrada: tensor([1.0000, 1.4142, 1.7321])
Suma total: tensor(6.)
Media: tensor(2.)


Good an bad Numpy copies

In [117]:
# Bad copy: torch -> numpy
x = torch.rand(2, 3)
y = x.numpy()

print(x, '\n')
print(y)

print('-'*80)

x.mul_(2)
print(x, '\n')
print(y)  # y también cambia

tensor([[0.5944, 0.9598, 0.7095],
        [0.0633, 0.9939, 0.4906]]) 

[[0.5944276  0.9598111  0.7094653 ]
 [0.0632748  0.9939202  0.49056375]]
--------------------------------------------------------------------------------
tensor([[1.1889, 1.9196, 1.4189],
        [0.1265, 1.9878, 0.9811]]) 

[[1.1888552 1.9196222 1.4189306]
 [0.1265496 1.9878404 0.9811275]]


In [118]:
# Good copy: torch -> numpy
x = torch.rand(2, 3)
y = x.clone().numpy()
# or y = x.numpy() + 0

print(x, '\n')
print(y)

print('-'*80)
x.mul_(2)
print(x, '\n')
print(y)  # y no cambia


tensor([[0.6087, 0.4910, 0.9568],
        [0.6861, 0.1714, 0.5433]]) 

[[0.6086822  0.49097043 0.9568026 ]
 [0.68607354 0.17142266 0.5432814 ]]
--------------------------------------------------------------------------------
tensor([[1.2174, 0.9819, 1.9136],
        [1.3721, 0.3428, 1.0866]]) 

[[0.6086822  0.49097043 0.9568026 ]
 [0.68607354 0.17142266 0.5432814 ]]


Copias en Numpy: buenas y malas prácticas

In [119]:
# Bad copy: numpy -> torch
z = np.random.random((3, 4))
zt = torch.from_numpy(z)
print(z, '\n')
print(zt)
print('-'*80)

zt.sub_(1)
# z también cambia
print(z, '\n')
print(zt)

[[0.09033858 0.15582642 0.45601287 0.64718604]
 [0.94897328 0.46516385 0.8994113  0.92628795]
 [0.3829978  0.27215685 0.13852498 0.60704889]] 

tensor([[0.0903, 0.1558, 0.4560, 0.6472],
        [0.9490, 0.4652, 0.8994, 0.9263],
        [0.3830, 0.2722, 0.1385, 0.6070]], dtype=torch.float64)
--------------------------------------------------------------------------------
[[-0.90966142 -0.84417358 -0.54398713 -0.35281396]
 [-0.05102672 -0.53483615 -0.1005887  -0.07371205]
 [-0.6170022  -0.72784315 -0.86147502 -0.39295111]] 

tensor([[-0.9097, -0.8442, -0.5440, -0.3528],
        [-0.0510, -0.5348, -0.1006, -0.0737],
        [-0.6170, -0.7278, -0.8615, -0.3930]], dtype=torch.float64)


In [120]:
# Good copy: numpy -> torch
z = np.random.random((3, 4))
zt = torch.tensor(z)
print(z, '\n')
print(zt)
print('-'*80)

zt.sub_(1)
# z no cambia
print(z, '\n')
print(zt)

[[0.64100821 0.92467473 0.92994408 0.51242633]
 [0.85812985 0.51525306 0.98704186 0.2754669 ]
 [0.49435604 0.53914499 0.57065675 0.42616435]] 

tensor([[0.6410, 0.9247, 0.9299, 0.5124],
        [0.8581, 0.5153, 0.9870, 0.2755],
        [0.4944, 0.5391, 0.5707, 0.4262]], dtype=torch.float64)
--------------------------------------------------------------------------------
[[0.64100821 0.92467473 0.92994408 0.51242633]
 [0.85812985 0.51525306 0.98704186 0.2754669 ]
 [0.49435604 0.53914499 0.57065675 0.42616435]] 

tensor([[-0.3590, -0.0753, -0.0701, -0.4876],
        [-0.1419, -0.4847, -0.0130, -0.7245],
        [-0.5056, -0.4609, -0.4293, -0.5738]], dtype=torch.float64)


GPU y CPU en PyTorch

In [121]:
if torch.cuda.is_available():
    print('Yes')
    dev = torch.device("cuda")
    
    x = torch.ones(2, 3, 4, device=dev)  # directly create a tensor on GPU
    y = torch.ones(2, 3, 4)
    y = y.to(dev)  # or .to("cuda")
    
    z = x + y
    z = z.to("cpu")  # or .to(dev)
    print(z)
    
else:
    print('No')

Yes
tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])


## Diferenciación

El problema es, que dada una función $f : \mathbb{R} \rightarrow \mathbb{R}$, computa su derivada con respecto a $x_i$:
$$
\frac{\partial f}{\partial x_i}
$$

Hence, tenemos que computar el gradiente * evaluado en un punto en particular:
$$
\nabla f(x) = \left( \frac{\partial f}{\partial x_1}, \frac{\partial f}{\partial x_2}, \ldots, \frac{\partial f}{\partial x_n} \right)
$$

#### Diferenciación simbólica

Supongamos $f(x) = sin(2x)$. Computar la derivada es sencillo:
$$
\frac{df}{dx} = 2cos(2x)
$$

en el punto 3.5 es

In [122]:
import sympy as sym

x = sym.symbols('x')

df = sym.diff(sym.sin(2 * x), x)
print(df)
df.subs(x, 3.5)

2*cos(2*x)


1.50780450868661

Pros:

- Diferenciación exacta
- Una vez que la derivada está computada, evaluarla en cualquier punto es rápido.

Contras:
- Computacionalmente costoso para funciones complejas.
- Para aplicaciones reales, diferenciacion simbólica no es práctica.


## Diferenciación numérica

Dada una función $f : \mathbb{R} \rightarrow \mathbb{R}$, la derivada en un punto $x$ se puede aproximar como:
$$
\frac{df}{dx} \approx \frac{f(x + h * e_i) - f(x)}{h}
$$
para un valor pequeño de $h$.

Donde $e_i$ es el elemento de la base canónica (un vector con 1 en la posición $i$ y 0 en las demás).
Esto para diferenciacion finita.

Imagina que $f(x) = sin(2x)$ y queremos la derivada en el punto 3.5.

In [123]:
import numpy as np

h = 1e-4
x0 = 3.5
n = 1

ei = np.diag(np.ones(n))
print(ei)

def f1(x):
    return np.sin(2 * x)

[[1.]]



In [124]:
val = (f1(x0 + h * ei[0]) - f1(x0)) / h
print(val.squeeze())

1.5076731013186073


Ahora con $f(x) = 3x_1x_3-x_2^2+5x_3^2$ computa la derivada para el punto (1, 2, 3):

$$
\nabla f(1, 2, 3) = \left( \frac{\partial f}{\partial x_1}, \frac{\partial f}{\partial x_2}, \frac{\partial f}{\partial x_3} \right)
$$

In [125]:
x0 = np.array([1.0, 2.0, 3.0])
n = 3
ei = np.diag(np.ones(n))
print(ei)

def f2(x):
    return 3 * x[0] * x[2] -2*x[1]**2 + 5 * x[2]**3

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [126]:
val = (f2(x0 + h * ei) - f2(x0)) / h
print(val)


[-1299997.          -920008.0002        80144.00450005]



El erro de paximación of forward finite difference is $O(h)$. vamos a intentar usar central finite difference, que tiene un error de $O(h^2)$:
$$
\frac{df}{dx} \approx \frac{f(x + h * e_i) - f(x - h * e_i)}{2h}
$$
par algun 0 < h << 1. donde $e_1$ Pertenece a la base canónica. y es el i elemento de la base canónica.

In [127]:
val = (f2(x0 + h * ei) - f2(x0 - h * ei)) / (2 * h)
print(val)


[  3.          -8.         144.00000005]


Pros:
- En algunos escenarios, la presicion es buena.
- Fácil de implementar.

Contras:
- La aproximación puede ser inexacta si h no es lo suficientemente pequeño.
- Depende del comportamiento local de la función. 

## Diferenciación automática

Supongamos que $f(x) = sin(2x)$ y computar la derivada en el punto 3.5.

In [128]:
import torch

x0 = torch.tensor(3.5, requires_grad=True)
print(x0)

tensor(3.5000, requires_grad=True)



In [129]:
f1 = torch.sin(2 * x0)
print(f1)

tensor(0.6570, grad_fn=<SinBackward0>)


In [130]:
f1 = f1.backward()
print(x0.grad)  # df/dx at x=3.5

tensor(1.5078)


Ahora con $f(x) = 3x_1x_3-x_2^2+5x_3^2$ computa la derivada para el punto (1, 2, 3):

$$
\nabla f(1, 2, 3) = \left( \frac{\partial f}{\partial x_1}, \frac{\partial f}{\partial x_2}, \frac{\partial f}{\partial x_3} \right)
$$

In [131]:
x0 = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(x0)

tensor([1., 2., 3.], requires_grad=True)


In [132]:
f2 = 3 * x0[0] * x0[2] - 2 * x0[1]**2 + 5 * x0[2]**3
print(f2)

tensor(136., grad_fn=<AddBackward0>)


### Visualización del grafo computacional en PyTorch

PyTorch permite inspeccionar el grafo de operaciones que se construye para calcular derivadas automáticas. El atributo `.grad_fn` de un tensor resultado muestra el nodo raíz del grafo. Podemos recorrer el grafo hacia atrás usando `.next_functions`.

A continuación se muestra cómo visualizar el grafo para la función $f(x) = 3x_1x_3-x_2^2+5x_3^3$ evaluada en $x=[1,2,3]$.

In [133]:
# Inspección básica del grafo computacional
print('grad_fn de f2:', f2.grad_fn)

# Recorrer el grafo hacia atrás
current = f2.grad_fn
for i in range(5):
    print(f'Paso {i}:', current)
    if hasattr(current, 'next_functions') and current.next_functions:
        current = current.next_functions[0][0]
    else:
        break

grad_fn de f2: <AddBackward0 object at 0x000001B5232DD630>
Paso 0: <AddBackward0 object at 0x000001B5232DD630>
Paso 1: <SubBackward0 object at 0x000001B522F287F0>
Paso 2: <MulBackward0 object at 0x000001B5232DD630>
Paso 3: <MulBackward0 object at 0x000001B522F287F0>
Paso 4: <SelectBackward0 object at 0x000001B5232DD630>


In [134]:
f2.backward()
print(x0.grad)  # df/dx at x=[1,2,3]



tensor([  9.,  -8., 138.])


## Simple ejemplo

Supón que lanzas una piedra de forma vertical cuya función de desplazamiento es:

$$
d(t) = -14t^2 + 23t + 2
$$

Contesta lo siguiente:

- Encuentra la velocidad en el tiempo $t_1 = \frac{23}{28}$
- Encuentra la aceleración cuando $t_2 = 3$


In [135]:
def d(t):
    return -14 * t**2 + 23 * t + 2

In [136]:
t1 =  torch.tensor(23/28, requires_grad=True)
t2 =  torch.tensor(3.0, requires_grad=True)

In [137]:
d1 = d(t1)

d1.backward()

print(t1.grad)  # dd/dt at t=23/28

tensor(0.)


In [138]:
a2 = torch.autograd.functional.hessian(d, t2)
a2

tensor(-28.)


## Uso de PyTorch para algoritmos de optimización de búsqueda en línea

In [139]:
def Rosenbrock(x):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    x = x.to(device)
    val = torch.zeros(1).to(device)
    for i in range(x.size(0)-1):
        val = val + 100 * (x[i+1] - x[i]**2)**2 + (1 - x[i])**2
    return val

In [140]:
def Sphere(x):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    x = x.to(device)
    return torch.sum(x**2)

Some inspection for sphere function

In [141]:
x1 = torch.ones(5, requires_grad=True)
x0 = torch.zeros(5, requires_grad=True)
xr = torch.rand(5, requires_grad=True)

fx1 = Sphere(x1)
fx0 = Sphere(x0)
fxr = Sphere(xr)

fx1.backward()
print(fx1)
print(x1.grad)
fx0.backward()
print(fx0)
print(x0.grad)
fxr.backward()
print(fxr)
print(xr.grad)

tensor(5., device='cuda:0', grad_fn=<SumBackward0>)
tensor([2., 2., 2., 2., 2.])
tensor(0., device='cuda:0', grad_fn=<SumBackward0>)
tensor([0., 0., 0., 0., 0.])
tensor(2.3822, device='cuda:0', grad_fn=<SumBackward0>)
tensor([0.6073, 1.8719, 0.2791, 1.5129, 1.8136])


In [142]:
x1 = torch.ones(5, requires_grad=True)
x0 = torch.zeros(5, requires_grad=True)
xr = torch.rand(5, requires_grad=True)

fx1 = Rosenbrock(x1)
fx0 = Rosenbrock(x0)
fxr = Rosenbrock(xr)

fx1.backward()
print(fx1)
print(x1.grad)
fx0.backward()
print(fx0)
print(x0.grad)
fxr.backward()
print(fxr)
print(xr.grad)

tensor([0.], device='cuda:0', grad_fn=<AddBackward0>)
tensor([0., 0., 0., 0., 0.])
tensor([4.], device='cuda:0', grad_fn=<AddBackward0>)
tensor([-2., -2., -2., -2.,  0.])
tensor([15.2723], device='cuda:0', grad_fn=<AddBackward0>)
tensor([-2.0064, -0.4229,  6.8545, 39.1322, 29.9902])


Definiendo un gradiente descendiente simple

In [ ]:
def my_GD(fun, dim, alpha, Iters):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    w = torch.rand(dim, requires_grad=True, device=device)
    print(w)
    fw = fun(w)
    print(fw)

    for i in range(Iters):
        fw.backward()
        with torch.no_grad():
            w -= alpha * w.grad
        w.grad.zero_()
        fw = fun(w)
        print(f'Iter {i+1}/{Iters}, f(w)={fw.item()}, w={w}')

    return w, fw
        

In [150]:
dim = 3
alpha = 1e-2
Iters = 1000

w, fw = my_GD(Sphere, dim, alpha, Iters)

print('_'*80)
print(w)
print(fw)

tensor([0.4221, 0.1114, 0.5157], device='cuda:0', requires_grad=True)
tensor(0.4566, device='cuda:0', grad_fn=<SumBackward0>)
Iter 1/1000, f(w)=0.43847212195396423
Iter 2/1000, f(w)=0.42110857367515564
Iter 3/1000, f(w)=0.4044326841831207
Iter 4/1000, f(w)=0.38841715455055237
Iter 5/1000, f(w)=0.37303581833839417
Iter 6/1000, f(w)=0.35826361179351807
Iter 7/1000, f(w)=0.34407639503479004
Iter 8/1000, f(w)=0.3304509222507477
Iter 9/1000, f(w)=0.3173650801181793
Iter 10/1000, f(w)=0.3047974705696106
Iter 11/1000, f(w)=0.29272744059562683
Iter 12/1000, f(w)=0.2811354398727417
Iter 13/1000, f(w)=0.27000245451927185
Iter 14/1000, f(w)=0.25931039452552795
Iter 15/1000, f(w)=0.24904169142246246
Iter 16/1000, f(w)=0.23917964100837708
Iter 17/1000, f(w)=0.22970813512802124
Iter 18/1000, f(w)=0.22061169147491455
Iter 19/1000, f(w)=0.21187546849250793
Iter 20/1000, f(w)=0.20348519086837769
Iter 21/1000, f(w)=0.19542719423770905
Iter 22/1000, f(w)=0.18768827617168427
Iter 23/1000, f(w)=0.180255815

In [151]:
dim = 20
alpha = 1e-3
Iters = 10000

w, fw = my_GD(Rosenbrock, dim, alpha, Iters)

print('_'*80)
print(w)
print(fw)

tensor([0.3099, 0.8220, 0.5308, 0.8162, 0.8132, 0.3858, 0.7630, 0.5595, 0.9252,
        0.7994, 0.0744, 0.4055, 0.7830, 0.0328, 0.4158, 0.4990, 0.4978, 0.7675,
        0.6864, 0.6770], device='cuda:0', requires_grad=True)
tensor([359.3570], device='cuda:0', grad_fn=<AddBackward0>)
Iter 1/10000, f(w)=159.0824737548828
Iter 2/10000, f(w)=132.75787353515625
Iter 3/10000, f(w)=118.56371307373047
Iter 4/10000, f(w)=108.37728118896484
Iter 5/10000, f(w)=100.3582763671875
Iter 3/10000, f(w)=118.56371307373047
Iter 4/10000, f(w)=108.37728118896484
Iter 5/10000, f(w)=100.3582763671875
Iter 6/10000, f(w)=93.65613555908203
Iter 7/10000, f(w)=87.7950210571289
Iter 8/10000, f(w)=82.51473999023438
Iter 9/10000, f(w)=77.68904876708984
Iter 6/10000, f(w)=93.65613555908203
Iter 7/10000, f(w)=87.7950210571289
Iter 8/10000, f(w)=82.51473999023438
Iter 9/10000, f(w)=77.68904876708984
Iter 10/10000, f(w)=73.26971435546875
Iter 11/10000, f(w)=69.24578094482422
Iter 12/10000, f(w)=65.614013671875
Iter 13/100