In [5]:
import torch
import numpy as np

In [6]:
x =  torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [7]:
y = torch.tensor([[1, 2, 3],[4, 5, 6]])
y

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
print(x.size())
print(y.size())

torch.Size([3])
torch.Size([2, 3])


In [9]:
x[0] += 10
print(x)

tensor([11,  2,  3])


In [10]:
print(x[0])

tensor(11)


In [11]:
x0_val = x[0].item()
print(x0_val)

11


Ejemplo de tensores

In [12]:
z = torch.ones(2,3)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
z = torch.rand(2, 3)
print(z)

tensor([[0.5017, 0.5443, 0.9535],
        [0.3639, 0.6167, 0.2533]])


In [15]:
z = torch.empty(2, 3)
print(z)

tensor([[4.4506e+20, 1.2612e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


### Que es un tensor?

Un tensor es una estructura de datos que generaliza los conceptos de escalares, vectores y matrices a dimensiones superiores. En términos simples:
- Un escalar es un tensor de orden 0 (un solo número).
- Un vector es un tensor de orden 1 (una lista de números).
- Una matriz es un tensor de orden 2 (una tabla de números con filas y columnas).

Un tensor puede tener más de dos dimensiones, lo que permite representar datos más complejos, como imágenes (3D), videos (4D) o cualquier otro tipo de datos multidimensionales. Los tensores son fundamentales en el aprendizaje profundo y se utilizan para almacenar y manipular datos en redes neuronales.

In [16]:
a = torch.tensor(-5.3)
print(a.size)
print(a)

<built-in method size of Tensor object at 0x000001EB1B04F610>
tensor(-5.3000)


In [17]:
a = torch.ones(2,3)
print(a.size())
print(a)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


La función `torch.ones(3, 4, 5)` crea un tensor de tres dimensiones (3D) donde:

- El primer número (`3`) indica que hay 3 bloques o matrices.
- El segundo número (`4`) indica que cada bloque tiene 4 filas.
- El tercer número (`5`) indica que cada fila tiene 5 columnas.

En términos generales, un tensor de forma `(3, 4, 5)` puede visualizarse como una colección de 3 matrices, cada una de tamaño 4x5. Más allá de matrices, los tensores permiten representar datos multidimensionales, como imágenes (por ejemplo, lotes de imágenes RGB pueden tener forma `(batch_size, canales, alto, ancho)`).

**Resumen:**  
- Escalar: tensor de 0 dimensiones (un solo número).
- Vector: tensor de 1 dimensión (una lista).
- Matriz: tensor de 2 dimensiones (tabla de números).
- Tensor 3D: colección de matrices (por ejemplo, `torch.ones(3, 4, 5)`).

Esto es útil en aprendizaje profundo para organizar datos complejos y trabajar con lotes de ejemplos, canales de color, secuencias, etc.

In [18]:
a = torch.ones(3,4,5)
print(a.size())
print(a)

torch.Size([3, 4, 5])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [ ]:
# 2 Grupos de 3 matrices de 4x5
a = torch.ones(2,3,4,5)
print(a.size())
print(a)

torch.Size([2, 3, 4, 5])
tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])


In [20]:
a = torch.ones(2,3,4,5,2)
print(a.size())
print(a)

torch.Size([2, 3, 4, 5, 2])
tensor([[[[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

          [[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]]],


         [[[1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.],
           [1., 1.]],

     